(function () {
  // Legend: # wall, . floor, W wire-covered floor (decorative only), N
  // snow-covered floor (the heater melts 10% of these on activation),
  // S safe zone (spawn, monsters can't enter), H the heater switch
  // (walk onto it to turn it on), C big 2x2 crate (solid, can't be
  // opened), D door (blocks until the heater's on), E exit room floor,
  // X exit trigger.
  const grid = [
    '##################################################################################################',
    '#SSSSSS..........####................####................####................####................#',
    '#SSSSSS.NNNNNNNN.####.WWNNNNWWNNNWNN.####.NNNNNNNNNNNNNN.####.NNNWNNWNNNNNNN.####.NNNNNNNNNNNNWN.#',
    '#SSSSSS.NNNNNNNN.####.NNNNNNNNWNNNNW.####.NNNNNNNNNNNNNN.####.NWNNNNNNWNWNNN.####.NWNNWWNNNNNNNW.#',
    '#SSSSSS.NNNNNNNN......NNNWNNNNWNNNNN......NNNNNNN.NWNWNN......NNNNWNNNNNNWNN......WNNNNNNNWNNWNN.#',
    '#SSSSSS.NNNNNWNN......NNNNNNNWNNNNNW......NNNNNWNWNNWNWN......NNNNNNNWWNNNNN......NWNWNN...NNWNN.#',
    '#SSSSSS.N.NNWNNN......NNNNNNW.NNNNNN......NNNNWWN.NNNNNN......NNNNNNN.NNNNNN......NNNNNW.H.NWNNN.#',
    '#.......NNNNNNNW......NNNNNWNWNNWNNN......NNNNNNWNNNWNNN......NNNNNNNNNNNNNN......WNNNNN...NNNNN.#',
    '#.W.NN.NNNNNNWWN.####.NNWNWNNNNNNNNN.####.NNNNWNWNWNWNNW.####.NNNNNNNNNNNWNN.####.WNNNNNNNNNNNNN.#',
    '#.NNNNNNNNWNNNNN.####.NWNNNNNNNWWNNN.####.NNNNWNNNNNNNNN.####.NNNNNN.NNWNNNW.####.NNNWNNNWNNNNNN.#',
    '#................####................####................####................####................#',
    '#######....################....################....################....################....#######',
    '#######....################....################....################....################....#######',
    '#######....################....################....################....################....#######',
    '#######....################....################....################....################....#######',
    '#................####................####................####................####................#',
    '#..NNNNNNNNNNNNW.####.NNNNN.WNNWNWNN.####.NNNNNNNNNNNWNN.####.NWWNNNNNNNNNW..####.NWNNNNWNNNNNNN.#',
    '#.NNNNNNNNNNNWNN.####.WWNNWNNNNNNNNN.####.NNNNWNNNWN.N.N.####.NNNNNWNNNNNNNN.####.WNNNWNNNWNWNNN.#',
    '#.NNNNNNNNNNNWNN......NNNNNNNNNNNNNN......NNNNNNNNNNNWNN......NNNNNNNNNNCCNN......NNWNNNN.NNNNNN.#',
    '#.NNNNWNNNNNNNNN......NWNNNNNNNNNNWN......NWNNNNNNNNNNNN......NNNWNNNNNNCCNN......NNNNNWNWNWNNNN.#',
    '#.NNWNNNN.NNNNNN......NNWNNNN.NNNNNN......NNNNNWN.NWNNNN......WWNNWNN.NNNNNW......NNNNNWN.NNNNNW.#',
    '#.NNWNNNNNNNNWWN......NNNNNNWNNNWNNN......NNNNNNNNNWNNNN......NWNNNNWNNNWNNN......NNNWNNWWNNNWNN.#',
    '#.WNNWNNNNNNWNNN.####.NNNNNNNNNNNWNN.####.NNNNNNNNNNNNN..####.NNNNNWWWNWNNNN.####.NNNNNNNNN.NNNN.#',
    '#.NNNNWNNNNNNNNN.####.NNNNN.NNNNNNNN.####.NWNNNNWNNNWNNN.####.NNNNNNWNNNNNNN.####.NNNNNNNNNNNNNN.#',
    '#................####................####................####................####................#',
    '#######....################....################....################....################....#######',
    '#######....################....################....################....################....#######',
    '#######....################....################....################....################....#######',
    '#######....################....################....################....################....#######',
    '#................####................####................####................####................#',
    '#.WWNNNNNNNNNNNN.####.WNWWNNNNNNNNNN.####.NNWNNWWNNNNNNN.####.NWNNNW.NNNNNNN.####.NWN.WNNNNNNNNN.#',
    '#.WWNNNNNNNNNNNN.####.NNNNNNNNNWNNNN.####.NNNNWNNNNNNNNN.####.NNNNNNNNNWWNWN.####.NNNNNNNNWNNNNN.#',
    '#.NNNNWWNNNNNNNN......NNNNNNNWNWNNNN......NNNNNNNNNNNNNN......NNNNNNNNNNNNNN......NNNNWWNNNWWNNN.#',
    '#.NNNCCNWNNNNNNW......NNWNNNNNNNNWWW......NWNNNCCNNNNNNN......NWNNNNNWNNNNWN......NNNNNNWNNNNNNN.#',
    '#.NNNCCNN.NNNNWN......NWNNWNN.NNNNNN......WNWNNCC.NNNWNN......NNWNWNN.NWNNNN......NNN.NNN.WNWNNN.#',
    '#.WNNNNNNWWNNNNN......NNNNNNNNNNNNNN......NNNNNNNNNNNNNN......NNNNWNNNNNNNNN......NNNNNNNNNWWNNN.#',
    '#.NNNNNNNNNNNNNN.####.NNWNWNNCCNNNNN.####.NWNNNNNNNNNNWN.####.NNNNNNNNNWNNWN.####.NNNNNNNNNNNNNN.#',
    '#.NNNNNNNNWNNNNN.####.NWNNNWNCCNNNWN.####.NNNNNNNNWNNNNN.####.NNNNNNNNNNNNNN.####.NNNNNNWNNWNNNN.#',
    '#................####................####................####................####................#',
    '#######....################....################....################....################DDDD#######',
    '#######....################....################....################....################DDDD#######',
    '#######....################....################....################....################DDDD#######',
    '#######....################....################....################....################DDDD#######',
    '#................####................####................####................####EEEEEEEEEEEEEEEE#',
    '#.NNNNNNNNWNNNNW.####.NNWNWNNNWNNNNW.####.NNNNNNNWNNNWNN.####.NN.WNNNNNNNNNN.####EEEEEEEEEEEEEEEE#',
    '#.NNWNNWNNNNNNNN.####.NNNNNNWNNNNNNN.####.NN.NNNNNNNNNNN.####.NNNNNNNNNNWNNN.####EEEEEEEEEEEEEEEE#',
    '#.NNNNWNNNNNNNWN......NNNWNNWWNNNNNN......NWNNNNNNNNNNWN......NNWNWNN.NNNNNN.DDDDEEEEEEEEEEEEEEEE#',
    '#.WNNNNNWNWNNNNN......NNNNNWNNNNNNNN......WNNNWNNNNNNNWN......NN.NNNNNNNNNNN.DDDDEEEEEEEEEEEEEEEE#',
    '#.NNNWWNN.NNNNNN......NNNNNNN.NWWNNN......NNNNNNN.NWNNNN......NNNNWNN.CCNNNN.DDDDEEEEEEEEXEEEEEEE#',
    '#.NNNNNNNNNNNNNN......NWNNNNNNNWNNNN......NNNWNNNNNNNNWN......NNNNWNNNCCNNNN.DDDDEEEEEEEEEEEEEEEE#',
    '#.NNNNNNNWNNNNNW.####.NNNNNNWNNNNNNN.####.NWNNNNNNNNNNNW.####.NNNNNNNNWNNNNN.####EEEEEEEEEEEEEEEE#',
    '#.NWNNNNNNNNNNNN.####.NNNNNNNNWNNNNN.####.NWNNNNNNNNNNNN.####.NWNNNNNNNNNNWN.####EEEEEEEEEEEEEEEE#',
    '#................####................####................####................####EEEEEEEEEEEEEEEE#',
    '##################################################################################################',
  ];

  window.LEVEL14 = {
    tileSize: 32,
    cols: grid[0].length,
    rows: grid.length,
    grid,
    spawn1: { x: 2, y: 2 },
    spawn2: { x: 3, y: 2 },
    monsterSpawns: [
      { x: 69, y: 46 }, { x: 89, y: 18 },
    ],
    heater: { x: 89, y: 6 },
    exitTrigger: { x: 89, y: 48 },
    safeZone: { x0: 1, y0: 1, x1: 6, y1: 6 },
    patrolPoints: [
      { x: 9, y: 6 }, { x: 29, y: 6 }, { x: 49, y: 6 }, { x: 69, y: 6 }, { x: 89, y: 6 }, { x: 9, y: 20 },
      { x: 29, y: 20 }, { x: 49, y: 20 }, { x: 69, y: 20 }, { x: 89, y: 20 }, { x: 9, y: 34 }, { x: 29, y: 34 },
      { x: 49, y: 34 }, { x: 69, y: 34 }, { x: 89, y: 34 }, { x: 9, y: 48 }, { x: 29, y: 48 }, { x: 49, y: 48 },
      { x: 69, y: 48 },
    ],
    crateSpawns: [
      { x: 44, y: 45 }, { x: 49, y: 4 }, { x: 2, y: 16 }, { x: 54, y: 17 }, { x: 52, y: 17 },
      { x: 68, y: 9 }, { x: 85, y: 30 }, { x: 3, y: 8 }, { x: 6, y: 8 }, { x: 91, y: 22 },
      { x: 68, y: 30 }, { x: 75, y: 16 }, { x: 27, y: 23 }, { x: 55, y: 22 }, { x: 85, y: 34 },
      { x: 27, y: 16 }, { x: 64, y: 44 }, { x: 64, y: 47 },
    ],
    bigCrateSpawns: [
      { x: 70, y: 48 }, { x: 5, y: 33 }, { x: 47, y: 33 },
      { x: 29, y: 36 }, { x: 72, y: 18 },
    ],
  };
})();
