(function () {
  // Legend: # wall, . floor, W wire-covered floor (decorative only), N
  // snow-covered floor (the heater melts 10% of these on activation),
  // S safe zone (spawn, monsters can't enter), H the heater switch
  // (walk onto it to turn it on), C big 2x2 crate (solid, can't be
  // opened), D door (blocks until the heater's on), E exit room floor,
  // X exit trigger.
  //
  // A 10x8 room lattice (80 rooms, 4x the original 5x4/20-room layout),
  // with a single gated entrance into the exit room rather than two.
  const grid = [
    '######################################################################################################################################################################################################',
    '#SSSSSS..........####................####................####................####................####................####................####................####................####................#',
    '#SSSSSS.NNNNWNWN.####.NNNNNNNNNNNNNN.####.NNNNWNNWNNNNNN.####.NNWNNNNNNNWNNN.####.NNNNNWNNNNNNNN.####.NNNNWNWNNNNNNN.####.NNWNNNNWNWNWNN.####.NNNNNNNNNWNNNN.####.NNNNNNWNNNNNNN.####.NNNNNNNNNNNNNW.#',
    '#SSSSSS.WNNNWNNN.####.NNWNNWNNNNNWNN.####.NWNNNWNNNNNNNN.####.NNWNNNNNNNNNNN.####.NNNWNNNWNNNNNW.####.NNNNNNNNNNWNNN.####.NNNWWWNNNNWNNN.####.WNWNNNWWNNN.NN.####.NNNNN.NNNNWNNN.####.NNNWNWWNNNWWNN.#',
    '#SSSSSS.NNNNNNNW......NNNNN.NWWNNNNN......NWNWNWNNNNNNWN......NNNNNNNNNNNNNN......NNNNNNNNWNNWNN......NNNNWNNNWNNNNN......NNNNNNNNNWNNNW......NNNNWNNNNNNNNN......WNNNWNNNNWNNNN......NNNNNNNNNNNNNN.#',
    '#SSSSSS.WNNNNNNN......NWNNNNNNNNNNWW......NNNNNNNNNNNWNN......NNNWNNWNNNWNNW......NWNNNNNNNNNWNN......WNNNNNNNNNNNWN......NWNNNNWNNNNNNN......NNNNNNNNNNNNWN......NNNWWNNNNNNNNN......WNNNNNNNNNNNNN.#',
    '#SSSSSS.N.NNNNNN......NNNNNNN.NNNNNN......NNNNNNN.NNNWNN......NNNNNNW.NNNNNW......NNNNNNN.NNNN.N......NNNNNNN.NNNNWN......NNNWNWN.NNNWNN......NNNNNNN.NWNNNN......NNNWNWN.NNNNNW......NNNNNWN.NWNWNN.#',
    '#.......WN.NNNWN......WNNNNNNNNNNNNN......NNNNNNWNNNNNNN......NNNNNNNNWNNNWN......NNNNWNWNNNNWNN......NNNNNNNNNNNNNW......NNNNWNWNWNNNNN......NNNNNNNNNNNNNN......NN.NNNNNNNNWWN......NNNNNNNNNNNNNN.#',
    '#.NNNNNNNNWWWNWN.####.NNNNNNNNNNNNNN.####.NNNNNNWNNNNNNN.####.NNNNNNNWNNNNNN.####.WNNWWNWNNNNWWW.####.NNNNNNWNWNNWNW.####.NNNNNNNWNNWNNN.####.NNNNNWWNNNNNNN.####.NNNNNNNNNNNNNN.####.WNNNNNWNNNNNNN.#',
    '#.WNNNNNWNNNNNNN.####.NWNNNNNNNNWNNN.####.NNNNNNWNNNNWNN.####.NNNNNNNNNNNNNN.####.NN.NNNNNNNNNNN.####.NNWNNNNNNNNNNN.####.NNNNNNNNNNNNNW.####.WNNNNNNNNNNNNN.####..NNNNNNNNNNNNN.####.NWNNNNNNNNNNNN.#',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#.WNNNNWNWWNWNNN.####.NNNNWNNNNNNNNN.####.NWNNNNNNNNNNNN.####.NNWWNNNNWWNNNN.####.NNNNNNNNNNNNNW.####..NWNWNWNNNNNWN.####.NNNNNNNWNNNNNN.####.NNNNNNNNNWNNNN.####.NWNNNNWNNNNWNN.####.NNWNNNNWNNWNNN.#',
    '#.NNNNNNNNWNWWNN.####.NNNNNNNNCCNNNN.####.NNWWNNNNNNNNNN.####.NNNNNNNNNNNNNN.####.NNNNNNWNNNNNNN.####.WNNWNNWWNNNNNN.####.NWNNNNNWNNNNNN.####.WWWNNNNNNNNNNN.####.NNNNNNNNNNNNNN.####.NNNNNNNNNWNNNN.#',
    '#.WNNNNWCCNNNNNN......NNWNNNNWCCNWNN......NNWNNNWWNNNNNN......NNNNNNNNWNNNNN......NNNWNNWNNNNNNW......NNNNNNNNNNNNNN......NNNNNWNCCNNWNN......NNNWNNNNNNWWNN......NNNNNNNNNNNNNW......NNNNNNNNWNWWNN.#',
    '#.NWNNNWCCNNNNWW......NNNNNN.NNNNWNN......WWWN.NNNNNNWNN......NNNNNNNNNNNWWN......NWNNNN...NNNNN......NNNNNNNW.NNNNN......NNNWN.NCCNNNNN......NNNNNNNNNNNNNN......NNWWNNNNWWNNNN......WNWNNNNNNNNNNW.#',
    '#.NNNNNNN.NWNWNN......NNNNNNN.NNNNNN......NNNWNNN.NNNNNN......NNNNNNN.NNNNNW......NNWNNN.H.NNNNN......NNWNNNN.NNNNNN......NNNWNNN.NNNNNN......NNNNNNN.NNNNNN......NNNNNNN.NNNNNN......NNNNNNN.N.WNNN.#',
    '#.NNNNNNNNNNNNNN......NNNNNNWNNWNNNN......WNNWNNNNNNWNNW......NNNNNNNNNNNWNN......NNNNNN...WNNNN......NNNNNWNN.NNNNN......NNNNNNNNNNNNNN......NNNNNNNNNNNNNN......NNNNCCW.NNNNNW......NNNNNNNWNNNNNN.#',
    '#.NNNNNNNNNNNNNN.####.WNNNNNNWNNNWNN.####.NNNWNNNWWNNNWW.####.NNWNNNNNWWNNNN.####.WNNNNNNNNNNNWN.####..NNNNNNNNNNWNN.####.NWNNWNNNWNNNNN.####.NNNNNNWNNNNWNN.####.NNNNCCNNNNNNNN.####.NNNWNWNNNNNNNN.#',
    '#.NNNNNNNNWNNNNN.####.NNNNNNNNWNNNNN.####.NNNNNNNNNNNNNN.####.NNNWNNNWNNNWNN.####.NNNWNNNNNWNNNN.####.NNNNNNNNNNWNNN.####.NNNNNNNNNNNNNN.####.NNNNNNNNNNNNNN.####.NNNWWNNNWNNNWN.####.WNNNNNNNNNNNNN.#',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#.NNNNNNWNNNWNNN.####.NNNNNNNNNNWNNN.####.NNNNWWNNNNNNNN.####.NNNNNNNNNNNNNW.####.NNWWWNNNNNNNNN.####.NWNNNNNNWWNNNN.####.WNNNWNNNNNNNNN.####.NNNNNNNNNNNWNN.####.NNNNNNWWNNNWNN.####.NWNNNNNNWN.WNN.#',
    '#.NNNNNNNNNNNNNN.####.NNNNNNNNNNNNNN.####.NNNNNNWNWNNNNN.####.WNNNNNNNNNNNNN.####.NNNNNNNNNWNNNN.####.NWNNNNWNNWWWWN.####.NNNNNNNNNNNNNN.####.NNNNNNNNNNNWNN.####.NNNNNNWNNNNNNN.####.NNNNNNNNNNNN.N.#',
    '#.NNNNNNNWNNNNNN......NWNNNWNNNWWNWN......NNNNWNNNNNNWNN......NNNWNNNNNNNNWN......NNNNNNNNNNNWNN......NNNWNNNNNNNNNN......NNNNNNNNNNWNNN......NWNNNNNNNNWWNN......NNNNNNNNNN.NNN......WNNNNNWWWNWNNN.#',
    '#.NNNNNNNNNNWNNN......NWNWNNNNNNNWNN......NNNWNNNNWNNWNN......WNNNNWNNNNNWNN......NNNNNWNNNNNNNW......WNNWNNNNN.NN.W......NNNNNNNNNNNNNN......NNNNNNNNNNNNNN......NNNNNNNWNNNNNN......NNNNNNNNNNNNNN.#',
    '#.NNNNNWN.NNNNNN......NNNNNWN.NNNWNN......NNNWNNN.WWNNNN......WNNNNNN.NNWNNN......NNNNNNN.NNWNNN......WNNNNNN.WNNNNN......NNNWNNW.WNNNW.......NNNNNWN.NNNNNN......NNNNNNN.WNNNNN......WNNNNNN.WNNNNN.#',
    '#.NNNNNNNNNNNNNN......NNNNNNNNNNNNNN......NNNNNN.NNNNNNN......NNNNNNWNWNNNNN......NWNNWNCCNNNWNN......N.NNNNNNWNNNWN......NNNNWWNNNNNNNN......NNNNNWNNNNNWNN......NNNNNNNNNNWNNW......NNNNNNNNNCCNNN.#',
    '#.NNNNWWNWNNNNNN.####.WNWWNWNNNNNNWN.####.NWNNNNNWNNNNNN.####.NNNNNNNNNNNWNN.####.NNNNNNCCNNNNNN.####.NNNNNNNNNNWNNN.####.WNNNNNNNNNNNNN.####.NW.NWNNNNNNNNN.####.NNNNNNNNNNNNNN.####.NNNNNNNNNCCNNN.#',
    '#.NNNNNNNNNNNNNN.####.NNNWNNWNNNNNNN.####.NNNNNNNNNNNNWW.####.NNNNNNNWNNNNNN.####.NWWNNNNNNNNNNN.####.NWNNNNNNNNNNNN.####.WNNNNNNNNNNNWN.####.NNNNNNNNNNNNNN.####.NNWNNNNNNNNWNN.####.NNNNNNWNNNNNWN.#',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#.NNNNNNNNNN.NWN.####.NNNWNNNNNNNWNN.####.NNWWNNNNNNWNNN.####.NNNNWNNNNNNWNN.####.NNNNNNNNNNNNWW.####.NNNNNNNWNNNNNN.####.WNNNWNNNNNNWNN.####.NNNNNWNWNNNNNN.####.NNNNNNNNNNNNNW.####.NNNNNWNNNNNWNN.#',
    '#.NNWNNNNNNNNNNW.####.WNNWNNNNWNNWNN.####.NNNNNNNNNNNNNN.####.NNNNWNNNNNNNNN.####.WNNWNNNNNNWNNN.####.NNNCCNNNWWNNNN.####.NNNNNNNNNNNNWN.####.NNNNWNNNNNNNNW.####.WNCCWNWNNNNNNN.####.NNNNNNNNNNNNNN.#',
    '#.NNNNNNNNNNNNNW......NWNWNNNNNWNNWN......NNNNNNWWNWNNNN......NNNNNNW.NNNNNW......NNNNNWNNNNNNNN......NNNCCNNWWNNNNN......NNNNNNNNNNNWNN......NNNNNNNNWNWNNN......NNCCNNNNNNNWNN......NNNNNNNNNNWNNN.#',
    '#.WNNNNNNNNNNNWW......NNNNNNNNNNNNNN......NWWNNNNNNWNWNN......NNNNNNNNNNNCCN......NNNNNNNNWWWWNN......NNNNNNNNNNWNNN......WWNNNNNNWWNNNW......NNNWNNNNNNNNNW......NNNWNNNWNNNNNN......NNNNWNNWNWNNWN.#',
    '#.NNNNNNW.NNNNNN......NNNNNNN.NNNWNN......NWWWNNN.NNNNNW......NNNNNNN.NNNCCN......NNNWNNN.NNNWNN......N.NNWNN.NNNNNN......NNNNNNN.NNNNNW......NNNNNNN.NNNWNN......NNNNNNN.NWWNNN......NNNNNNN.NNNCCN.#',
    '#.WN.NNNNNNNNNWN......NWNNNNNNNNNNNN......NNNNNNNNNNNNNN......NNNWNNNN.NNNWN......NNNNNWNNNNNNNN......NNNNNNNNNNWNNW......NNNNNNNNNNCCNN......WWNNNNNNWNNNNN......NNNNWNWNNNWNNW......NNNWNNNNNNNCCN.#',
    '#.WNNWNNNNNWNNNN.####.NNWNNNWNWNNNNN.####.WNWNNNWNNNNNNN.####.WNNNNNWNNNNNWN.####.NNNCCNNNNNNNWW.####.NNNNNNNNNNNNNN.####.NNWNNNWNNNCCNN.####.NNNWNNNNNWNNWW.####.NN.NNNNNNNNNNN.####.NNNNNNNNNNNNNN.#',
    '#.NNNNNWNNNWNNNN.####.NNNWNNNNNNNNNN.####.NWWNWNWNNNNNNN.####.WNNNWNNNNNNNNN.####.NNNCCNNNWNNNNN.####.NNNWNNNNNNNNNN.####.NNWNNNNWNWNNNN.####.NNNNNNNNNNNNNN.####.NWNNNNNNNNNNNN.####.NNNNNNNWNNNWNN.#',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#.NNNNNNNNNNWWNN.####.NNWNNWNNNNNNNN.####.NNNWNNNNNNNWNN.####.NNNNNNNNNNNNNN.####.NWNNNNWNNNNNNW.####.WNNNWNNNNNNNNN.####.NNNNNNNNNNNNNW.####.NNNNNNNNNNNWNN.####.NNNNNNWWNNNNNN.####.NWWNNNNNNNNNNW.#',
    '#.NNNNWWNNNNNNNN.####.NWNNNNNWNNWNNN.####.NNNNNNNNNNNNNN.####.NWWNNNNNNN.WNN.####.NNNNNNNWNNNNNW.####.NNNNNNNNNNNNNN.####..NNNNWNNNNNNNN.####.NNWNNNNNNNNNNN.####.NNNNNNNNNNNNNN.####.NNNNNNNNNNNNNN.#',
    '#.NNW.NNNNNNNNNN......NWNNNNNNWNNNNW......NNNWWNNNNNNNNN......NNNNNNWWWNNNNN......NWNNNNNNNNNNNN......N.NNNNNWNWNNNN......NNNNNNNWNNNNNN......NNWWNNNNNNNNNN......NNNNNNNNNWNNNN......NNNNNNNWNNNNWN.#',
    '#.NNNWNWNNNNNNNN......WNNNNCCNNNNWNN......NNNNNNNWNWNWNN......NWNNNNNNNN.NNN......NNNWNNNNNNNNWW......WNNNWWNNNNNWNN......NNNWNNNNWNNNNN......NNWNNNNNNNNNNN......NNNNNNNNNWNNWN......NWNNNNNNNNWNNN.#',
    '#.NNNNNNW.NNNNNN......NNNNNCC.NNNNNN......NNNWNNN.NWWNNN......NNNCCNN.NNNNNN......NNNNNNN.NNNWNN......NNNNNNW.WNNWNN......WNNNNWN.NNNNNW......WNNNN.N.WNNNNN......NWWNNNN.NNNNNN......NWNWNNN.WNNNNN.#',
    '#.NNNNNNNNNNNNWN......NNNNNNNNNNNNNN......NNNNNNNNNWNNNW......NWNCCNNNNWNNNN......NNNWNNNNNNNNNN......NNNNNNNNNNNNWN......NNNWNNNNWCCNNN......NNNNNNNNNNNNNN......WNNNNNNNNNNNNW......NNNNNNNNNNNWNN.#',
    '#.NNNNNNNNNNNNNW.####.NNNNNNNNNNNNNN.####.WNNNNNNNNNWNNN.####.WNNNNNNNNNNNNN.####.NNNNNNWNNNNNNN.####.WNNNNWNNNNNNNN.####.WWNNWNWNNCCNNN.####.NNWNNNNNNNNNNW.####.NNNNNNNNNNNNNN.####.NNNNNNNNNNNNNN.#',
    '#.NWWNNNNNNNNNNN.####.NNNW..NNNNNNNN.####.NNNNNNNNNNNWNN.####.WNNNNNNNNNWWNN.####.NWNNNWNWNNNNNW.####.NNNNNNNNWWNWNW.####.NNNNWNNNWNNNNN.####.NNNNNNNNNNNNNW.####.NNNNNNN.NNNN.N.####.NNNNNNNNNNNNNN.#',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#.NNWNNNNNNNNNNW.####.WNNNNNNNNNNNNN.####.NNNNWNNNNNNNNN.####.NWWNWNNNNNNNWN.####.NNNNNNNNNNNNNN.####.NNNNNNNNNNWNNN.####.NNNNNNNNNNNWN..####.NNNNNNNNNNWNNN.####.NWNNNNNNNNNNNN.####.NNNNNNNNNNNNW..#',
    '#.NWNNWNNNNNNNWN.####.WNNWN.NNNNNNNN.####.NNNWNWCCNN.NNN.####.NNNNNNWNNNWNNN.####.NNWNNNNNNNNNNN.####.NNNNNNNWNNNNNN.####.WWNNWNNNWNNNNN.####.NNNNNNNWNNWNNN.####.NNNNNNNNNNNNNN.####.NNNNNNNNNNNNNN.#',
    '#.NNNNNNNNNWNWWN......WNNNNWWNNNNWNN.......NNNNNCCNNNN.N......NNWNNN.NNNNNNN......NNNNNNNNNNNNNN......NNNNNNNNNNNNNN......NNNNNWNNNNNNNW......NWNWNNNNNNNNNN......NNNNNNNNNNNNNN......NNNNNNNNNWNNNN.#',
    '#.WNNNNWNNWNNNNN......NNNNNNNNNNNNNN......NNNNNNNNNNNNNN......NNWNNNNWNNWNWN......NNNNNNNNNNNNNN......NNNNNNNNNNNNNN......W.NNNNNNNNNNWN......NWWNWNNNNNNNNN......NNNWNNNNNNNNNN......NNWNWWNNNNWNNN.#',
    '#.NNNNNNN.NNWWNN......NNNNNNN.NNNNNN......NNNWNWN.NNNNWN......NNNNNNN.NNNNNN......NNNNNNW.WNNNNW......NNNNNNN.WN.NNN......NNN.NWN.WNNWNN......NNNNNNW.CCNNNN......NNNNNNN.CCNNNN......NNNNNNW.NNNNNN.#',
    '#.NNNNNNNNNNNNNN......NNNCCNNNNNNWNN......NW.NNNNNNNNNNN......WWNNWWNNNNNWNN......NNNNNWNWNNNNNN......NNNNNNNNNWNNNN......WNNNWNNNNNNN.N......NNNWNNNNCCNNNN......WNNNNNNNCCNN.N......NNNNNNNNNNNNNN.#',
    '#.NNNNNNNNNNNNNN.####.NNNCCWNWNNNNNN.####.NNNWWWWNNNNNN..####.WNNNNNWNNNNNWN.####.WNNNWNNNWNWNNN.####.NNNNNWWWNCCNNN.####.NNNNNNNWNNNNNN.####.NNWNNNNNNNNNWN.####.WNNNNNNNNNNNNN.####.NNNNNNNNNNNNNN.#',
    '#.NNNNNNNNNNNNNN.####.NNNNWNWNNNNNNN.####.NNWNNNNNNNNNNN.####.NWNNNNNNNNNNNN.####.N.NNNWNWNNNNNN.####.NNNNNNWNNCCNNW.####.NNNNNNNNNWNNNN.####.WWNNNWNNNNNWWW.####.NNWNNNNNWNNNNN.####.NNNNNNNNNNNNNN.#',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#######....################....################....################....################....################....################....################....################....################....#######',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#.NNNNNNNNNNNWNW.####.NNNNNNNNNW.NNN.####.NNNNNNNNNNNNNN.####.NWNNNNWNWWNNNN.####..NNWNNNNNNNWNN.####.NNNWNNNNNNNWNN.####.NNNWNNNNNNNNWN.####.NWNNNNNNNNWNNN.####.NNNNNNNNNNNNNN.####.NNNNNNNNNNNNNN.#',
    '#.NNWNNNNNNNNCCN.####.NNNNNNNNNNNNNN.####.NNNNNNNNNWNNNN.####.NNNNNNNWNWNNNW.####.NNNCCNNNNNNNNN.####.NNNNNNWWNNNNNN.####.NNNCCNNNNNNNNN.####.NWNNNNNNNNNWNN.####.NNNNNNNNNNNNWN.####.WNNNNN.NNNNNNN.#',
    '#.NWNWNNNNNNWCCN......NNNNNNNWNWNNWN......WNNNNNNNWNNNNN......NNNNNNNNNNNWNN......NNNCCWNWNNNNNN......NNNWNNNNNNNNNN......NNWCCNNNNNNNNN......NNNNNNNNNNNNNN......NNNNNNNNNNNWNN......NWNWNNN.NNNWNN.#',
    '#.NNNNNNNNNNWWNW......NNNWNNNNNWNNNW......WNNNNNWNWNNNNN......WWNWWNNNNNNNNN......NNNWNNNNNNNNNN......NNNNNNNNNNNNNN......WNNNNNNNNNNNNN......NNNNNNNNNNNNNN......WNNNNNNNNWNNNW......NNNNNNNNNNWNNN.#',
    '#.NNNNNNN.NNWNNN......NNWNNNN.WNNNNN......NNWNWNN.NNNNNN......NWWNNNN.NNWWNN......NNNNWNN.NNNNNN......NNNNNNN.NNNNNN......NNNNNNN.NNNNNN......NNNNNNW.NNNNNW......NWNNNCC.NNNNNN......NNNNNWW.NNNNN..#',
    '#.NWNNNNNNNNNNN.......NN.NNNNNNNNNNN......NNNNNNNNNNNNNN......NWNNNNNWNNNNNN......NWNNNNNNNNNNNN......NNWNNNNNNNNNNN......NNNNNNWNWNNWNN......NNNNNNNNNNNNNN......NNNNNCCNNWWWWN......NNWNWNNNWNNNNN.#',
    '#.NNNNNWN.NNNNNN.####.NNNNWNWNNNNNNN.####.NNNNNWNNWWNNNN.####.WNNNNNN.NNNNNN.####.NNWNNNNNNNNNNN.####.NNNWNNNNNWNNNN.####.NNWNNWWNNWNNNN.####.NNNWNNNNNNNNNN.####.NN.NNWNNNWNNWN.####.NNNNNWNNNWWNWN.#',
    '#.NNNNWNNNNNNNNW.####.NNNNNNNNNNNNNN.####.NNNNNNNNNWNNNN.####.NWWNNNNNNNNNNN.####.NNNN.NNNNNNNNN.####.NNWNNNNNNNNNNN.####.NNNNNNNNNNNNNN.####.NWNNNNWNWNNNW..####.NNNNNNNNNWWNWN.####.NNNNNNNNNNWNNN.#',
    '#................####................####................####................####................####................####................####................####................####................#',
    '#######....################....################....################....################....################....################....################....################....################DDDD#######',
    '#######....################....################....################....################....################....################....################....################....################DDDD#######',
    '#######....################....################....################....################....################....################....################....################....################DDDD#######',
    '#######....################....################....################....################....################....################....################....################....################DDDD#######',
    '#................####................####................####................####................####................####................####................####................####EEEEEEEEEEEEEEEE#',
    '#.NNNNWNNNNNNNNN.####.NNWN.NNNNNNNNN.####.NNNNNNNNNWNNNN.####.NNNNNNWNNWNNNN.####.NNNNNNNNNNWNNN.####.NNWNNWNNNNNNNW.####.NNNNNNNNNWNNNN.####.NNNNNNNNNNNNNN.####.NNWNWNNNNNWNNN.####EEEEEEEEEEEEEEEE#',
    '#.NWNNNNNNNNNNWN.####.NNNNNNWNNNNNNN.####.NNNWNNNNNNNWNN.####.NNNNNNNWNNNNNN.####.NWNNNNNNNNNNNN.####.NWNNNNNNNNNWNN.####.NNNNNNNNNNNNNN.####.NNNNWNNNNWNNNN.####.NNNNNNNNNNNNNN.####EEEEEEEEEEEEEEEE#',
    '#.NNNNNNWNNNNWNN......NNNNNNNNNNWNNN......NNNNNWNNNWNNNN......NNNNNWNNNNNWNN......NNNNNNNNNNNNNN......NWNNWNNNNNNNNN......NNNNNNNWNNNNNN......NNNNNNNNNNNNNN......NNNWNNNNNNNNNN.####EEEEEEEEEEEEEEEE#',
    '#.WNNNNNNNNWNNNN......NNNNWNNNNNNNNN......NNWNWNNNNNNNWW......NNNNNNNNNNNNNN......WNNNWNNNNNNNNN......NNNNNNNWWNNNNN......NNWNWNNNNNNNWN......NNWNNWNWNNNNNN......NNNNNNNNWNNNNN.####EEEEEEEEEEEEEEEE#',
    '#.NNNNNNN.NNNNNN......NWNN.NN.NNNNNN......NNNNWNN.NNWWNN......N.NNNNN.NNNNNN......NNNNNNN.WNNNNN......NNNNNNW.NNNNNN......NNWNNNN.NNNNNN......NNNNWNW.NNNNNN......NNNNNNN.NNNNNN.####EEEEEEEEXEEEEEEE#',
    '#.NNNNWNNWNN.WNW......NNNNNNNNNNNNWN......NWWNNWNNNNNNWW......NNNNNNNNNNNNNN......NNNNNNNNNNWNNN......NNNNNNNNNNNNNN......NNNNNNNNNNWNNN......NWNNNNNNNNNNNN......NNNNNNNNNNNNNN.####EEEEEEEEEEEEEEEE#',
    '#.NNNNNNNNNNNNNN.####.NNNNNNNNWNNCCN.####.N.NNNNNNNNNNNN.####.NNNNNNNNNNNNWN.####.NNNNNNWNNNNNNN.####.WNNNCCNWWNNNNN.####.NNNNNNNNNNWNNN.####.NNNNWWNNNWNNWN.####.NNNNNWNNNNWNNW.####EEEEEEEEEEEEEEEE#',
    '#.NNWNNNWNNWNNWN.####.NWNWNNNNNNNCCN.####.NNNNNNNNNNNNNN.####.NNNNNNNNNNNNWN.####.NNNNNWNNNNNNNN.####.WNWNCCNNNNNNNN.####.NNNNNNNNNNNNNW.####.NNNWNNNNNNNNNN.####.NWNNNNNWNNNNNN.####EEEEEEEEEEEEEEEE#',
    '#................####................####................####................####................####................####................####................####................####EEEEEEEEEEEEEEEE#',
    '######################################################################################################################################################################################################',
  ];

  window.LEVEL14 = {
    tileSize: 32,
    cols: grid[0].length,
    rows: grid.length,
    grid,
    spawn1: { x: 2, y: 2 },
    spawn2: { x: 3, y: 2 },
    monsterSpawns: [
      { x: 189, y: 88 }, { x: 69, y: 46 },
    ],
    heater: { x: 89, y: 20 },
    exitTrigger: { x: 189, y: 104 },
    safeZone: { x0: 1, y0: 1, x1: 6, y1: 6 },
    patrolPoints: [
      { x: 9, y: 6 }, { x: 29, y: 6 }, { x: 49, y: 6 }, { x: 69, y: 6 }, { x: 89, y: 6 }, { x: 109, y: 6 },
      { x: 129, y: 6 }, { x: 149, y: 6 }, { x: 169, y: 6 }, { x: 189, y: 6 }, { x: 9, y: 20 }, { x: 29, y: 20 },
      { x: 49, y: 20 }, { x: 69, y: 20 }, { x: 89, y: 20 }, { x: 109, y: 20 }, { x: 129, y: 20 }, { x: 149, y: 20 },
      { x: 169, y: 20 }, { x: 189, y: 20 }, { x: 9, y: 34 }, { x: 29, y: 34 }, { x: 49, y: 34 }, { x: 69, y: 34 },
      { x: 89, y: 34 }, { x: 109, y: 34 }, { x: 129, y: 34 }, { x: 149, y: 34 }, { x: 169, y: 34 }, { x: 189, y: 34 },
      { x: 9, y: 48 }, { x: 29, y: 48 }, { x: 49, y: 48 }, { x: 69, y: 48 }, { x: 89, y: 48 }, { x: 109, y: 48 },
      { x: 129, y: 48 }, { x: 149, y: 48 }, { x: 169, y: 48 }, { x: 189, y: 48 }, { x: 9, y: 62 }, { x: 29, y: 62 },
      { x: 49, y: 62 }, { x: 69, y: 62 }, { x: 89, y: 62 }, { x: 109, y: 62 }, { x: 129, y: 62 }, { x: 149, y: 62 },
      { x: 169, y: 62 }, { x: 189, y: 62 }, { x: 9, y: 76 }, { x: 29, y: 76 }, { x: 49, y: 76 }, { x: 69, y: 76 },
      { x: 89, y: 76 }, { x: 109, y: 76 }, { x: 129, y: 76 }, { x: 149, y: 76 }, { x: 169, y: 76 }, { x: 189, y: 76 },
      { x: 9, y: 90 }, { x: 29, y: 90 }, { x: 49, y: 90 }, { x: 69, y: 90 }, { x: 89, y: 90 }, { x: 109, y: 90 },
      { x: 129, y: 90 }, { x: 149, y: 90 }, { x: 169, y: 90 }, { x: 189, y: 90 }, { x: 9, y: 104 }, { x: 29, y: 104 },
      { x: 49, y: 104 }, { x: 69, y: 104 }, { x: 89, y: 104 }, { x: 109, y: 104 }, { x: 129, y: 104 }, { x: 149, y: 104 },
      { x: 169, y: 104 },
    ],
    crateSpawns: [
      { x: 12, y: 105 }, { x: 164, y: 92 }, { x: 147, y: 62 }, { x: 10, y: 7 }, { x: 192, y: 30 }, { x: 172, y: 32 },
      { x: 5, y: 60 }, { x: 114, y: 33 }, { x: 103, y: 35 }, { x: 86, y: 93 }, { x: 123, y: 75 }, { x: 69, y: 92 },
      { x: 72, y: 61 }, { x: 24, y: 91 }, { x: 70, y: 49 }, { x: 110, y: 21 }, { x: 52, y: 73 }, { x: 135, y: 34 },
      { x: 26, y: 100 }, { x: 26, y: 104 }, { x: 110, y: 19 }, { x: 26, y: 65 }, { x: 42, y: 74 }, { x: 174, y: 65 },
      { x: 167, y: 3 }, { x: 162, y: 9 }, { x: 164, y: 50 }, { x: 135, y: 72 }, { x: 28, y: 19 }, { x: 112, y: 76 },
      { x: 27, y: 73 }, { x: 46, y: 19 }, { x: 94, y: 6 }, { x: 155, y: 93 }, { x: 63, y: 104 }, { x: 54, y: 74 },
      { x: 102, y: 22 }, { x: 134, y: 77 }, { x: 191, y: 20 }, { x: 48, y: 35 }, { x: 125, y: 76 }, { x: 153, y: 3 },
      { x: 32, y: 86 }, { x: 111, y: 33 }, { x: 84, y: 9 }, { x: 164, y: 7 }, { x: 43, y: 106 }, { x: 103, y: 60 },
      { x: 102, y: 16 }, { x: 188, y: 87 }, { x: 144, y: 36 }, { x: 72, y: 59 }, { x: 169, y: 65 }, { x: 174, y: 77 },
      { x: 4, y: 49 }, { x: 27, y: 4 }, { x: 195, y: 72 }, { x: 44, y: 77 }, { x: 12, y: 44 }, { x: 82, y: 86 },
      { x: 55, y: 78 }, { x: 27, y: 65 }, { x: 15, y: 91 }, { x: 122, y: 59 }, { x: 127, y: 19 }, { x: 83, y: 79 },
      { x: 68, y: 74 }, { x: 9, y: 92 }, { x: 195, y: 90 }, { x: 103, y: 48 }, { x: 194, y: 31 }, { x: 169, y: 21 },
    ],
    bigCrateSpawns: [
      { x: 105, y: 45 }, { x: 73, y: 47 }, { x: 164, y: 45 }, { x: 8, y: 18 }, { x: 170, y: 76 }, { x: 193, y: 48 },
      { x: 13, y: 87 }, { x: 25, y: 77 }, { x: 33, y: 106 }, { x: 129, y: 18 }, { x: 85, y: 50 }, { x: 191, y: 35 },
      { x: 27, y: 61 }, { x: 131, y: 63 }, { x: 167, y: 90 }, { x: 88, y: 35 }, { x: 48, y: 73 }, { x: 125, y: 87 },
      { x: 85, y: 87 }, { x: 106, y: 106 }, { x: 30, y: 17 }, { x: 132, y: 49 }, { x: 65, y: 62 }, { x: 111, y: 78 },
      { x: 166, y: 21 }, { x: 150, y: 76 },
    ],
  };
})();
