(function () {
  // Legend: # wall, N snow-covered floor (decorative only), S safe
  // zone (spawn, the boss can't enter), G phase-2 gate (a wall until
  // the boss drops to 15 HP, then opens into the chase hallway).
  // No fixed weak-point tile -- torches spawn randomly across the
  // open floor in phase 1, and at fixed points down the hallway in
  // phase 2 (see game15.js's spawnTorch).
  //
  // A wide-open rectangular arena (35x21) up top, with the whole thing
  // visible on screen at once in phase 1 -- see game15.js's ZOOM. A
  // long, narrow, featureless corridor hangs off its south wall behind
  // the gate for the phase-2 chase; the camera switches to a normal
  // follow-cam down there instead of the fixed arena view.
  const grid = [
    '###################################',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#SSSSNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#SSSSNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#SSSSNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#SSSSNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#SSSSNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#SSSSNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN#',
    '###############GGGGG###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
    '###############NNNNN###############',
  ];

  window.LEVEL15 = {
    tileSize: 32,
    cols: grid[0].length,
    rows: grid.length,
    grid,
    arenaRows: 21,
    spawn1: { x: 2, y: 9 },
    spawn2: { x: 2, y: 11 },
    safeZone: { x0: 1, y0: 7, x1: 4, y1: 12 },
    monsterSpawns: [{ x: 17, y: 10 }],
    crateSpawns: [{ x: 8, y: 4 }, { x: 8, y: 16 }, { x: 25, y: 4 }, { x: 15, y: 4 }, { x: 15, y: 16 }, { x: 27, y: 4 }, { x: 12, y: 10 }, { x: 22, y: 16 }],
    gate: { x0: 15, x1: 19, y: 20 },
    hallway: { x0: 15, x1: 19, y0: 21, y1: 80 },
    hallwayTorchPoints: [{ x: 17, y: 36 }, { x: 17, y: 51 }, { x: 17, y: 66 }],
  };
})();
